apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: ecommer-app
        image: rukevweubio/ecommerce-app:latest
        ports:
        - containerPort: 80
