apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: rukevweubio/ecommerce-app


    newName: rukevweubio/ecommerce-app
    newTag: latest

replicas:
  - name: ecommerce-app
    count: 2


namePrefix: dev-